Repository gksgpd97/android-wanted-LocationHistoryApp, pull requests merged in 2022-09, with the labels that each got.

#6 Junbo feat/#1 구글맵 연결 작업
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/preonboarding/locationhistory/ui/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, feat

#8 [fix] dao 메소드 이름 변경, 날짜 컬럼 문제해결, 테스트코드 수정
  app/src/androidTest/java/com/preonboarding/locationhistory/local/dao/HistoryDaoTest.kt
  app/src/main/java/com/preonboarding/locationhistory/local/dao/HistoryDao.kt
  app/src/main/java/com/preonboarding/locationhistory/local/repository/HistoryRepositoryImpl.kt
Labels: fix

#10 refactor:> util패키지 local에서 분리 및 Converter.kt 내 메소드 top-level로 변경
  app/src/androidTest/java/com/preonboarding/locationhistory/local/dao/HistoryDaoTest.kt
  app/src/main/java/com/preonboarding/locationhistory/local/util/Converter.kt
  app/src/main/java/com/preonboarding/locationhistory/util/Converter.kt
Labels: refactor
